package com.mycompany.agenciatributariapresentacion;

import com.mycompany.agenciatributarianegocio.Control.Icontrol;
import com.mycompany.agenciatributarianegocio.DTO.PersonaDTO;
import com.mycompany.agenciatributarianegocio.DTO.TramiteDTO;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.FileNotFoundException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import org.jdesktop.swingx.autocomplete.ObjectToStringConverter;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTable;

/**
 *
 * @author TeLesheo
 */
public class BuscarReporte extends javax.swing.JFrame {
    Icontrol control;
    PersonaDTO persona;
    Calendar fechaI,fechaF;
    /**
     * Creates new form BuscarReporte
     */
    public BuscarReporte(Icontrol control) {
        this.control=control;
        initComponents();
        ocultarBotonesExtra();
        centrarFormulario(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cbTipo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFechaIncio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFechafinal = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable = new javax.swing.JTable();
        btnGenerarPDF = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        radio3 = new javax.swing.JRadioButton();
        radio2 = new javax.swing.JRadioButton();
        radio1 = new javax.swing.JRadioButton();
        labelReferencia = new javax.swing.JLabel();
        btnElegir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Buscar Reporte");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Placa", "Licencia" }));
        cbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Filtros de busqueda");

        jLabel5.setText("Fecha inicio");

        jLabel6.setText("Fecha final");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtable);

        btnGenerarPDF.setText("Generar PDF");
        btnGenerarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarPDFActionPerformed(evt);
            }
        });

        btnAtras.setText("Cancelar");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio3);
        radio3.setText("Periodo");
        radio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio2);
        radio2.setText("Nombre");
        radio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio1);
        radio1.setText("Tipo");
        radio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio1ActionPerformed(evt);
            }
        });

        labelReferencia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelReferencia.setText("Elige una persona para observar sus tramites");

        btnElegir.setText("Elegir");
        btnElegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElegirActionPerformed(evt);
            }
        });

        btnCancelar.setText("Atras");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(radio1))
                                        .addGap(53, 53, 53)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(radio2)))
                                    .addComponent(btnBuscar))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(74, 74, 74)
                                        .addComponent(radio3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(117, 117, 117)
                                        .addComponent(jLabel5))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtFechafinal, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFechaIncio, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(labelReferencia))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(btnElegir)
                        .addGap(65, 65, 65)
                        .addComponent(btnCancelar)))
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAtras)
                        .addGap(56, 56, 56)
                        .addComponent(btnGenerarPDF)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(345, 345, 345))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(radio1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addComponent(btnBuscar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radio3)
                            .addComponent(radio2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaIncio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechafinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelReferencia)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnElegir)
                    .addComponent(btnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerarPDF)
                    .addComponent(btnAtras))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoActionPerformed

    private void radio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio2ActionPerformed
        limpiarTabla();
        desactivarDecoradorAutocompletado();
        txtNombre.setText("");
        txtFechaIncio.setText("");
        txtFechafinal.setText("");
        cargarTipo(2);  
        activarDecoradorAutocompletado();
    }//GEN-LAST:event_radio2ActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (radio1.isSelected()) {
            String textoSeleccionado = (String)cbTipo.getSelectedItem();
            llenarTablaTramitesMejorado(control.consultaEspecificasTipoPeriodo(textoSeleccionado, 1, fechaI, fechaF));
        }else if (radio2.isSelected()) {
            String textoSeleccionado = txtNombre.getText();
            llenarTablaPersonas(control.consultaEspecificaPersonas(textoSeleccionado, 2));
            btnElegir.setVisible(true);
            btnCancelar.setVisible(true);
            labelReferencia.setVisible(true);
        }else if (radio3.isSelected()) {
            if (!txtFechaIncio.getText().isEmpty() && !txtFechafinal.getText().isEmpty()) {
                fechaI=parseCalendar(txtFechaIncio.getText());
                fechaF=parseCalendar(txtFechafinal.getText());
            }
            llenarTablaTramitesMejorado(control.consultaEspecificasTipoPeriodo("", 2, fechaI, fechaF));
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElegirActionPerformed
        // Obtener la fila seleccionada
        int filaSeleccionada = jtable.getSelectedRow();

        // Verificar si se seleccionó alguna fila
        if (filaSeleccionada != -1) {
            obtenerPersonaTabla(filaSeleccionada);
            limpiarTabla();
            llenarTablaTramitesMejorado(control.consultarTramites("", 2, persona));
        }else{
            JOptionPane.showMessageDialog(null, "No se ha seleccionado una fila");
        }
    }//GEN-LAST:event_btnElegirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiarTabla();
        ocultarBotonesExtra();
        txtNombre.setText("");
        txtFechaIncio.setText("");
        txtFechafinal.setText("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void radio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio3ActionPerformed
        ocultarBotonesExtra();
        txtNombre.setText("");
    }//GEN-LAST:event_radio3ActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        PaginaInicio frmInicio=new PaginaInicio(control);
        frmInicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void radio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio1ActionPerformed
        ocultarBotonesExtra();
        txtFechaIncio.setText("");
        txtFechafinal.setText("");
        txtNombre.setText("");
        
    }//GEN-LAST:event_radio1ActionPerformed

    private void btnGenerarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarPDFActionPerformed
        if (tablaEstaVacia(jtable)) {
            JOptionPane.showConfirmDialog(null, "No se ha realizado ninguna consulta");
            return;
        }else{
            String outputFile = System.getProperty("user.home") + "\\Downloads\\" + "Reporte.pdf";
            List<reporte> pdf=new ArrayList<>();
            SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
            for (int i = 0; i < jtable.getRowCount(); i++) {
                String tipo = jtable.getValueAt(i, 1).toString();
                String fechaEmisionString = jtable.getValueAt(i, 2).toString();
                 Date fechaEmision = null;
                try {
                    fechaEmision = formato.parse(fechaEmisionString);
                } catch (ParseException ex) {
                    Logger.getLogger(BuscarReporte.class.getName()).log(Level.SEVERE, null, ex);
                }
                float costo = Float.parseFloat(jtable.getValueAt(i, 3).toString());
                String nombre = jtable.getValueAt(i, 4).toString();
                String apellidoPaterno = jtable.getValueAt(i, 5).toString();
                String apellidoMaterno = jtable.getValueAt(i, 6).toString();

                // Concatenar los nombres y apellidos para obtener el nombre completo
                String nombreCompleto = nombre + " " + apellidoPaterno + " " + apellidoMaterno;

                // Verificar el valor del tipo y asignar el texto correspondiente
                String tipoExpedicion;
                if (tipo.equals("placas")) {
                    tipoExpedicion = "Expedición de placas";
                } else {
                    tipoExpedicion = "Expedición de Licencia";
                }

                // Crear un objeto reporte con los datos obtenidos y añadirlo a la lista
                reporte reporteActual = new reporte(tipoExpedicion, nombreCompleto, fechaEmision.toString(), String.valueOf(costo));
                pdf.add(reporteActual);
            }        
            System.out.println(pdf.size());
            try {
                Map<String, Object> parameters = new HashMap<String, Object>();
                
//                 Cargar los datos en un JRBeanCollectionDataSource
                JRBeanCollectionDataSource beanColData = new JRBeanCollectionDataSource(pdf);

//                 Cargar el archivo JRXML del reporte
                InputStream reportFile = getClass().getResourceAsStream("/Tramitereporte.jrxml");

//                 Compilar el reporte
                JasperReport jasperReport = JasperCompileManager.compileReport(reportFile);

//                 Llenar el reporte con los datos
                JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, beanColData);

//                 Exportar el reporte a un archivo PDF
                JasperExportManager.exportReportToPdfFile(jasperPrint, outputFile);

//                 Visualizar el reporte en el visor Jasper
                JasperViewer jasperViewer = new JasperViewer(jasperPrint, false);
                jasperViewer.setVisible(true);

            } catch (JRException ex) {
                Logger.getLogger(BuscarReporte.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_btnGenerarPDFActionPerformed

    
    private void cargarTipo(int tipo){
        
        if (tipo==2) {
            JList listaSugerencia= new JList(control.obtenerPersonas(2));
            AutoCompleteDecorator.decorate(listaSugerencia, txtNombre, ObjectToStringConverter.DEFAULT_IMPLEMENTATION);
        }
        
    }
    
    private void desactivarDecoradorAutocompletado() {
        txtNombre.setDocument(new javax.swing.text.PlainDocument());
    }
    
    private void activarDecoradorAutocompletado() {
        cargarTipo(buttonGroup1.getSelection().getMnemonic());
    }
    
    private void limpiarTabla() {
        DefaultTableModel model = new DefaultTableModel();
        jtable.setModel(model);
    }
    
    private void llenarTablaTramitesMejorado(List<TramiteDTO> tramitesDTOList){
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        // Definir las columnas de la tabla
        String[] columnas = {"ID", "Tipo", "Fecha Emisión", "Costo", "Nombre", "Apellido Paterno", "Apellido Materno"};

        // Crear un DefaultTableModel con las columnas
        DefaultTableModel model = new DefaultTableModel(columnas, 0);

        // Recorrer la lista de TramiteDTO y agregar cada objeto como una fila en el modelo de la tabla
        for (TramiteDTO tramiteDTO : tramitesDTOList) {
            Object[] fila = {
                tramiteDTO.getId(),
                tramiteDTO.getTipo(),
                dateFormat.format(tramiteDTO.getFechaEmision().getTime()),
                tramiteDTO.getCosto(),
                tramiteDTO.getPersona().getNombres(),
                tramiteDTO.getPersona().getApellidoPaterno(),
                tramiteDTO.getPersona().getApellidoMaterno()
            };
            model.addRow(fila);
        }

        // Establecer el modelo de la tabla
        jtable.setModel(model);
    }
    
    private void llenarTablaPersonas(List<PersonaDTO> personasDTOList){
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String [] columnas = {"ID","Nombre","Apellido Paterno","Apellido Materno","CURP","RFC","FechaNac","Telefono"};
        
        DefaultTableModel model = new DefaultTableModel(columnas, 0);
        
        for (PersonaDTO personaDTO:personasDTOList) {
            Object[] fila = {
                personaDTO.getId(),
                personaDTO.getNombres(),
                personaDTO.getApellidoPaterno(),
                personaDTO.getApellidoMaterno(),
                personaDTO.getCurp(),
                personaDTO.getRfc(),
                personaDTO.getFechaNacimiento(),
                personaDTO.getTelefono()
            };
            model.addRow(fila);
        }
        
        jtable.setModel(model);
    }
    
    private void ocultarBotonesExtra(){
        btnElegir.setVisible(false);
        btnCancelar.setVisible(false);
        labelReferencia.setVisible(false);
    }

    private void obtenerPersonaTabla(int filaSeleccionada){
        
            // Obtener los datos de la fila seleccionada
            Long id = Long.parseLong(jtable.getValueAt(filaSeleccionada, 0).toString());
            String nombres = jtable.getValueAt(filaSeleccionada, 1).toString();
            String apellidoPaterno = jtable.getValueAt(filaSeleccionada, 2).toString();
            String apellidoMaterno = jtable.getValueAt(filaSeleccionada, 3).toString();
            String curp = jtable.getValueAt(filaSeleccionada, 4).toString();
            String rfc = jtable.getValueAt(filaSeleccionada, 5).toString();
            Calendar fechaNacimiento = (Calendar) jtable.getValueAt(filaSeleccionada, 6); 
            String telefono = jtable.getValueAt(filaSeleccionada, 7).toString();

            
            persona=new PersonaDTO();
            persona.setId(id);
            persona.setNombres(nombres);
            persona.setApellidoPaterno(apellidoPaterno);
            persona.setApellidoMaterno(apellidoMaterno);
            persona.setCurp(curp);
            persona.setRfc(rfc);
            persona.setFechaNacimiento(fechaNacimiento);
            persona.setTelefono(telefono);
            
    }
    
    private Calendar parseCalendar(String dateString) {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        try {
            Date date = dateFormat.parse(dateString);
            Calendar calendar = Calendar.getInstance();
            calendar.setTime(date);
            return calendar;
        } catch (ParseException ex) {
            ex.printStackTrace();
            return null;
        }
}
    
    private boolean tablaEstaVacia(JTable tabla) {
        return tabla.getRowCount() == 0;
    }
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(BuscarReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(BuscarReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(BuscarReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(BuscarReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new BuscarReporte().setVisible(true);
//            }
//        });
//    }

    public static void centrarFormulario(JFrame frame) {
        // Obtener el tamaño de la pantalla
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        // Obtener el tamaño del formulario
        Dimension frameSize = frame.getSize();
        // Calcular la posición x para centrar el formulario
        int x = (screenSize.width - frameSize.width) / 2;
        // Calcular la posición y para centrar el formulario
        int y = (screenSize.height - frameSize.height) / 2;
        // Establecer la posición del formulario
        frame.setLocation(x, y);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnElegir;
    private javax.swing.JButton btnGenerarPDF;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtable;
    private javax.swing.JLabel labelReferencia;
    private javax.swing.JRadioButton radio1;
    private javax.swing.JRadioButton radio2;
    private javax.swing.JRadioButton radio3;
    private javax.swing.JTextField txtFechaIncio;
    private javax.swing.JTextField txtFechafinal;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
